### ISSUE TITLE
Conditional token values

### ISSUE THREAD

**Issue by romainmenke** [design-tokens/community-group#169]
see : https://github.com/design-tokens/community-group/issues/2

This issue was focussed on "theming" and already contains some great thoughts on that but I don't think that themes are the right abstraction. I also do not want to derail that thread.

--------

The basic premise is fairly simple and shared with the concept of themes :

**Change token values when X changes, where X is something external to the tokens file**

Examples of factors that could affect token values :

- screen size
- ability to display certain colors on a screen (srgb, display-p3)
- user preferences for color schemes (dark, light)
- applying different branding (brand X, brand Y)
- platform type (Android, iOS, Web)
- media type (screen, print)
- support for features

The most mature system/API that exists for this is most likely Conditional At Rules in CSS (`@supports` and `@media` specifically)

In CSS Conditional At Rules "wrap" around style declarations.

```css
.foo {
  color: cyan;
}


@media (min-width: 300px) {
  .foo {
    color: purple;
  }
}

@media screen and (prefers-color-scheme: dark) {
  .foo {
    color: yellow;
  }
}
```

For Design Tokens I think the inverse makes the most sense.
A token describes a base value and a list of conditional values.

```json
{
  "$value": "cyan",
  "$conditionalValues": [
    {
      "conditions": [{
        "name": "screen-min-width",
        "value": "300px"
      }],
      "value": "purple"
    },
    {
      "conditions": [
        {
          "name": "media-type",
          "value": "screen"
        },
        {
          "name": "color-scheme",
          "value": "dark"
        }
      ],
      "value": "yellow"
    }
  ]
}
```

The exact data shape for `"conditions"` is likely non-ideal for all possible cases.
But I think it illustrates the point.

Condition names would need to be a specced list.
Condition values per name would also need to be specced.

--------

Design tools would provide UI to assign conditional values on tokens and would also use them.

- Artboards might match certain conditions based on config (artboard size, color scheme, ...)
- Certain actions might trigger certain conditions (printing a document)
- ....

--------

Translation tools could generate the code for the conditionals so that developers can use a single token name while still having a dynamic outcome.

--------

Specialised tools could provide validation.
You might want to "lint" a tokens file and check that all colors have a dark and light variant.

**Comment by phun-ky** [comment]
To be honest, I do not think logic or conditions should exist in the spec. Design tokens are meant to contain _raw_ values to be processed.

**Comment by romainmenke** [comment]
> To be honest, I do not think logic or conditions should exist in the spec. Design tokens are meant to contain raw values to be processed.

I actually agree and should have included this in my initial statement.
I think this is best solved by having multiple token files.

But if something like "theming" is handled by the spec I think it should be more abstract and include the cases listed above.

------

In our PostCSS plugin for style dictionary we solve this outside of token files : https://github.com/csstools/postcss-plugins/tree/main/plugins/postcss-design-tokens#is

```css
@design-tokens url('./tokens-light.json') format('style-dictionary3');
@design-tokens url('./tokens-dark.json') when('theme-blue') format('style-dictionary3');

.foo {
	color: design-token('color.background.primary');
}
```

The value of `color.background.primary` changes depending on user config when building the CSS.

The same mechanic can be expanded on later to include conditions typically found in `@media` or `@supports`.
